name: Run BitBot

# Only allow manual trigger
on:
  workflow_dispatch:

jobs:
  run-bitbot:
    runs-on: windows-latest

    steps:
      # 1. Checkout your repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3. Install FFmpeg
      - name: Install FFmpeg
        run: choco install ffmpeg -y

      # 4. Install Python dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # 5. Run the bot
      - name: Run BitBot
        run: python BitBot/BitBot.py
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
